
import Navbar from "@/components/custom/Navbar";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import Banner from "@/components/custom/Banner";
import Footer from "@/components/custom/Footer";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "ComputoAkash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
             <Navbar/>
             <Toaster/>
            {children}
            <Banner/>
            <Footer/>
          </ThemeProvider>
       
       
      </body>
    </html>
  );
}
