
import Navbar from "@/components/custom/Navbar";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import Banner from "@/components/custom/Banner";
import Footer from "@/components/custom/Footer";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";



export const metadata = {
  title: "ComputoAkash",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
  <body >
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <AuthProvider>
        <Navbar />
        <Toaster />
        {children}
        <Banner />
        <Footer />
      </AuthProvider>

    </ThemeProvider>


  </body>
    </html >
  );
}
